### ISSUE TITLE
cannot install on os-x

### ISSUE THREAD

**Issue by dcsan** [Samurais/node-word2vec#2]
The error here prevented the install:

../app/reader.cc:80:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance());

```
➜ npm i node-word2vec-reader

> node-word2vec-reader@1.0.5 install /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader
> node-gyp rebuild

  CXX(target) Release/obj.target/word2vec/app/addon.o
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.7.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name addon.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu core2 -target-linker-version 351.8 -v -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=lldb -coverage-notes-file /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader/build/Release/obj.target/word2vec/app/addon.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0 -dependency-file ./Release/.deps/Release/obj.target/word2vec/app/addon.o.d.raw -MT Release/obj.target/word2vec/app/addon.o -D NODE_GYP_MODULE_NAME=word2vec -D USING_UV_SHARED=1 -D USING_V8_SHARED=1 -D V8_DEPRECATION_WARNINGS=1 -D _DARWIN_USE_64_BIT_INODE=1 -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D BUILDING_NODE_EXTENSION -I /Users/dc/.node-gyp/10.1.0/include/node -I /Users/dc/.node-gyp/10.1.0/src -I /Users/dc/.node-gyp/10.1.0/deps/uv/include -I /Users/dc/.node-gyp/10.1.0/deps/v8/include -I ../../nan -stdlib=libc++ -stdlib=libc++ -Os -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader/build -ferror-limit 19 -fmessage-length 132 -stack-protector 1 -fblocks -fno-threadsafe-statics -fobjc-runtime=macosx-10.7.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o Release/obj.target/word2vec/app/addon.o -x c++ ../app/addon.cc
clang -cc1 version 9.1.0 (clang-902.0.39.2) default target x86_64-apple-darwin17.7.0
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/src"
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/deps/uv/include"
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/deps/v8/include"
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Users/dc/.node-gyp/10.1.0/include/node
 ../../nan
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
  CXX(target) Release/obj.target/word2vec/app/reader.o
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.7.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name reader.cc -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu core2 -target-linker-version 351.8 -v -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=lldb -coverage-notes-file /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader/build/Release/obj.target/word2vec/app/reader.gcno -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0 -dependency-file ./Release/.deps/Release/obj.target/word2vec/app/reader.o.d.raw -MT Release/obj.target/word2vec/app/reader.o -D NODE_GYP_MODULE_NAME=word2vec -D USING_UV_SHARED=1 -D USING_V8_SHARED=1 -D V8_DEPRECATION_WARNINGS=1 -D _DARWIN_USE_64_BIT_INODE=1 -D _LARGEFILE_SOURCE -D _FILE_OFFSET_BITS=64 -D BUILDING_NODE_EXTENSION -I /Users/dc/.node-gyp/10.1.0/include/node -I /Users/dc/.node-gyp/10.1.0/src -I /Users/dc/.node-gyp/10.1.0/deps/uv/include -I /Users/dc/.node-gyp/10.1.0/deps/v8/include -I ../../nan -stdlib=libc++ -stdlib=libc++ -Os -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++14 -fdeprecated-macro -fdebug-compilation-dir /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader/build -ferror-limit 19 -fmessage-length 132 -stack-protector 1 -fblocks -fno-threadsafe-statics -fobjc-runtime=macosx-10.7.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o Release/obj.target/word2vec/app/reader.o -x c++ ../app/reader.cc
clang -cc1 version 9.1.0 (clang-902.0.39.2) default target x86_64-apple-darwin17.7.0
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/src"
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/deps/uv/include"
ignoring nonexistent directory "/Users/dc/.node-gyp/10.1.0/deps/v8/include"
ignoring nonexistent directory "/usr/include/c++/v1"
#include "..." search starts here:
#include <...> search starts here:
 /Users/dc/.node-gyp/10.1.0/include/node
 ../../nan
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
In file included from ../app/reader.cc:13:
../app/vector_utils.h:30:23: warning: comparison of integers of different signs: 'int' and 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >::size_type' (aka 'unsigned long') [-Wsign-compare]
    for (int i = 0; i < str.length(); i++) {
                    ~ ^ ~~~~~~~~~~~~
../app/reader.cc:80:37: error: no matching member function for call to 'NewInstance'
    info.GetReturnValue().Set(cons->NewInstance());
                              ~~~~~~^~~~~~~~~~~
/Users/dc/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate function not viable: requires single argument 'context', but
      no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/dc/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../app/reader.cc:102:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value param0(info[0]->ToString());
                        ^
/Users/dc/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dc/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../app/reader.cc:151:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../app/reader.cc:163:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../app/reader.cc:175:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../app/reader.cc:191:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value param0(info[0]->ToString());
                        ^
/Users/dc/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dc/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../app/reader.cc:199:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
         ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../app/reader.cc:225:10: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
         ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../app/reader.cc:248:25: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  v8::String::Utf8Value param0(info[0]->ToString());
                        ^
/Users/dc/.node-gyp/10.1.0/include/node/v8.h:2821:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dc/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../app/reader.cc:314:8: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::GetCurrentContext()->Global(), cb, argc, argv);
       ^
../../nan/nan.h:929:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
10 warnings and 1 error generated.
make: *** [Release/obj.target/word2vec/app/reader.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dc/dev/rikai/nap/web-app/server/node_modules/node-word2vec-reader
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-word2vec-reader@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-word2vec-reader@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dc/.npm/_logs/2018-08-23T19_35_50_467Z-debug.log
➜  server git:(241-suggest-sim-words-202-pipe-wip) ✗
```

**Comment by dcsan** [comment]
however I was able to compile the google tools fine on their own

this is using `gcc`

```
➜  google git:(master) ✗ make
make: Nothing to be done for `all'.
➜  google git:(master) ✗ make clean
rm -rf word2vec word2phrase distance word-analogy compute-accuracy
➜  google git:(master) ✗ make
gcc word2vec.c -o word2vec -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -fno-stack-protector
gcc word2phrase.c -o word2phrase -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -fno-stack-protector
gcc distance.c -o distance -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -fno-stack-protector
distance.c:31:8: warning: unused variable 'ch' [-Wunused-variable]
  char ch;
       ^
1 warning generated.
gcc word-analogy.c -o word-analogy -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -fno-stack-protector
word-analogy.c:31:8: warning: unused variable 'ch' [-Wunused-variable]
  char ch;
       ^
1 warning generated.
gcc compute-accuracy.c -o compute-accuracy -lm -pthread -O3 -march=native -Wall -funroll-loops -Wno-unused-result -fno-stack-protector
compute-accuracy.c:28:109: warning: unused variable 'ch' [-Wunused-variable]
  char st1[max_size], st2[max_size], st3[max_size], st4[max_size], bestw[N][max_size], file_name[max_size], ch;
                                                                                                            ^
1 warning generated.
chmod +x *.sh
```

**Comment by dcsan** [comment]
the error line in question seems to call into a V8 

![image](https://user-images.githubusercontent.com/514002/44549285-351cbc80-a753-11e8-89d0-2b4dea816c1e.png)

deep in the native V8 function wrappers

```c++
inline
MaybeLocal<v8::Object> NewInstance(v8::Local<v8::ObjectTemplate> h) {
  v8::Isolate *isolate = v8::Isolate::GetCurrent();
  v8::EscapableHandleScope scope(isolate);
  return scope.Escape(h->NewInstance(isolate->GetCurrentContext())
                          .FromMaybe(v8::Local<v8::Object>()));
}
```

**Comment by dcsan** [comment]
I'm wondering if its something to do with apple using clang rather than gcc 
I don't know much about node-gyp, if there's a way to tell it to use a different compiler?
https://github.com/nodejs/node-gyp

this line prior I assume is `eval` to include the nan V8 bindings.
```
                        "<!(node -e \"require('nan')\")"],
```
